language: php

branches:
  only:
    - master
    - develop

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir build
  - make phpunit
  - make phpcs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
